spring:
  application:
    name: SpringCloudOauth2FandB
security:
  oauth2:
    client:
      clientId: 1086402888409307
      clientSecret: a3f5cb80933e754dabc7c43e89abd368
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me